=== FilmakademieRnd/Frapper/resources/nodetype.dtd
<!ELEMENT nodetype (parameter|parameters)*>
<!ATTLIST nodetype
	name			CDATA				#REQUIRED
	category (Animation|Cameras|Character|Compositing|Geometry|Images|Input|Lights|Network|Rendering|Shading|Tracking|Utility|S3D|Solver|rtSolver) 
										#REQUIRED
	color			CDATA				#REQUIRED
	plugin			CDATA				#REQUIRED
>

<!ELEMENT parameter (literal|separator)*>
<!ATTLIST parameter
	name			CDATA				#REQUIRED
	type			(Bool|Int|UnsignedInt|Float|String|Filename|Color|Enumeration|TextInfo|Command|Geometry|Light|Camera|Image|Group|PlugIn|Generic) 
										#REQUIRED
	size			CDATA	            #IMPLIED
    multiplicity	CDATA				#IMPLIED
    defaultValue	CDATA				#IMPLIED
    visible			(true|1|false|0)	#IMPLIED
    enabled			(true|1|false|0)	#IMPLIED
    readOnly		(true|1|false|0)	#IMPLIED
    selfEvaluating	(true|1|false|0)	#IMPLIED
    affects			CDATA				#IMPLIED
    description		CDATA				#IMPLIED
    unit			CDATA				#IMPLIED
    pin				(in|out)			#IMPLIED
    inputMethod		(SpinBox|SliderPlusSpinBox)	
										#IMPLIED
    minValue		CDATA				#IMPLIED
    maxValue		CDATA				#IMPLIED
    stepSize		CDATA				#IMPLIED
    filter			CDATA				#IMPLIED
>

<!ELEMENT literal EMPTY>
<!ATTLIST literal
	name			CDATA				#REQUIRED
	value			CDATA				#IMPLIED
>

<!ELEMENT parameters (parameter|parameters)*>
<!ATTLIST parameters
	name			CDATA				#IMPLIED
	enabled			(true|false)		#IMPLIED
    visible			(true|false)	#IMPLIED

>

<!ELEMENT separator EMPTY>

=== FilmakademieRnd/Frapper/plugins/nodes/Utility/PoemAnalyser/poemanalyser.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         test.xml
  Description:  Contains the XML description of Test nodes.
  Author:       Stefan Habel <stefan.habel@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="PoemAnalyser" category="Utility" color="250,100,50" plugin="poemanalyser.dll">
  <parameters>
    <parameters name="Simple">
      <parameter name="Description" type="TextInfo" defaultValue="This group contains parameters to read the analysis of a poem and tagged it accordingly."/>      
      <parameter name="Filename DAT" type="Filename"/>
      <parameter name="Filename FOR" type="Filename"/>
      <parameter name="Poem text" type="Filename" />
      <parameter name="Author" type="String" visible="true" />
      <parameter name="Title" type="String" visible="true" />
    
      
      <!--<parameter name="Command" type="Command"/>-->
    </parameters>
    
    <!-- input parameters -->
    
    <parameter name="String in" type="String" pin="in" visible="false"/>
    <parameter name="Filename in" type="Filename" pin="in" visible="false"/>

    
    <!-- output parameters -->
    
    <parameter name="String out" type="String" pin="out" visible="true"/>
    <parameter name="Filename out" type="Filename" pin="out" visible="false"/>
    
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Shading/GaussBlur/gaussblur.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         depthoffield.xml
  Description:  Contains the XML description of Blur nodes.
  Author:       Nils Zweiling <nils.zweiling@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="GaussBlur" category="Shading" color="7, 45, 87" plugin="ShadingTemplate.dll">
  <parameters>
    <parameter name="Shader Name" type="String" defaultValue="GaussBlurShader"/>
    <parameter name="Resource Location" type="String" defaultValue="resources/GaussBlur_Shader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Shader Parameters Pass 0">
      <parameter name="BlurWidth" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="3.0" stepSize="0.01"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Shading/LightWarping/lightwarping.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--
  Project:      Filmakademie Application Framework
  File:         lightwarping.xml
  Description:  Contains the XML description of AmbientOcclusion nodes.
  Author:       Felix Bucella <felix.bucella@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="LightWarping" category="Shading" color="7, 45, 87" plugin="lightwarping.dll">
  <parameters>
    <parameter name="Resource Group Name" type="String" defaultValue="LightWarpingNode"/>
    <parameter name="Reload" type="Command"/>
    <parameter name="Light Description File" type="Filename" filter="Light Description Files (*.txt)"/>
    <parameter name="Input Map Normal" type="Image" pin="in" selfEvaluating="false"/>
    <parameter name="Input Map Hessian" type="Image" pin="in" selfEvaluating="false"/>
    <parameter name="Input Map View" type="Image" pin="in" selfEvaluating="false"/>
    <parameter name="Input Map Lights" type="Image" pin="in" visible="false"/>
    <parameter name="Input Map Powers" type="Image" pin="in" visible="false"/>
    <parameter name="Number Of Lights" type="Float" defaultValue="24.0"/>
    <parameter name="cmax" type="Float" defaultValue="1.0" maxValue="40.0" stepSize="1.0"/>
    <parameter name="exponent" type="Float" defaultValue="1.0" maxValue="500.0"/>
    <parameter name="fresnel" type="Float" defaultValue="0.0"/>
    <parameter name="diffuse" type="Float" size="3" defaultValue="0.5, 0.5, 0.5"/>
    <parameter name="specular" type="Float" size="3" defaultValue="0.5, 0.5, 0.5"/>
    <parameter name="contrast" type="Float" defaultValue="0.0"/>
    <parameter name="enable" type="Bool" defaultValue="1"/>
    <parameter name="aniso" type="Bool" defaultValue="1"/>
    <parameter name="lightscale" type="Float" defaultValue="10.0" minValue="0.1"  maxValue="100.0"/>
    <parameter name="envsize" type="Float" defaultValue="1000000.0" maxValue="10000000.0"/>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/brightnessContrast.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         bloom.xml
  Description:  Contains the XML description of Bloom nodes.
  Author:       Simon Spielmann <sspielma@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="BrightnessContrast" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="BrightnessContrastCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="BrightnessContrastShader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Shader Parameters Pass 0">
      <parameter name="brightness" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="10.0" stepSize="0.1"/>
      <parameter name="contrast"   type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="5.0" stepSize="0.1"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Images/ImageFile/imagefile.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         ImageFile.xml
  Description:  Contains the XML description of ImageFile nodes.
  Author:       Stefan Habel <stefan.habel@filmakademie.de>, Nils Zweiling <nils.zweiling@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="ImageFile" category="Images" color="173, 255, 173" plugin="imagefile.dll">
  <parameters>
    <parameter name="Image File" type="Filename" filter="Image Files (*.bmp *.png *.jpg *.exr)"/>
    <parameter name="Missing Frame Color" type="Color" defaultValue="0, 0, 0"/>
    <parameter name="Image Dimensions" type="TextInfo" />
    <parameter name="Scale in %" type="Int" minValue="1" maxValue="300" defaultValue="100" inputMethod="SliderPlusSpinBox" stepSize="1" unit=""/>
    <parameter name="Reset Image Size" type="Command" />
    <parameters name="Image Sequence" enabled="false">      
      <parameter name="Sequence Length" type="TextInfo" />
      <parameter name="Use Image Sequence" type="Bool" defaultValue="false" />
      <parameter name="Start Frame" type="Int" minValue="-5000" maxValue="5000"/>
      <parameter name="End Frame" type="Int" minValue="-5000" maxValue="5000"/>
      <parameter name="Start Frame Offset" type="Int" minValue="-5000" maxValue="5000"/>
      </parameters>       
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/depthoffield.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         depthoffield.xml
  Description:  Contains the XML description of DepthOfField nodes.
  Author:       Nils Zweiling <nils.zweiling@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="DepthOfField" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="DepthOfFieldCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="DepthOfFieldShader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Input Map Blur" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Input Map Depth" type="Image" pin="in" selfEvaluating="false"/>
    </parameters> 
    <parameters name="Shader Parameters Pass 0">
      <parameter name="focalPlane" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.0" minValue="0.0" maxValue="0.1" stepSize="0.001"/>
      <parameter name="radius" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.0" minValue="0.0" maxValue="0.1" stepSize="0.001"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Shading/CelShading/CelShading.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         watercolor.xml
  Description:  Contains the XML description of Watercolor nodes.
  Author:       Michael Bußler<@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-Württemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="CelShading" category="Shading" color="7, 45, 87" plugin="ShadingTemplate.dll">
  <parameters>
    <parameter name="Shader Name" type="String" defaultValue="CelShadingShader"/>
    <parameter name="Resource Location" type="String" defaultValue="resources/CelShading_Shader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Image" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Normal Map" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Input Textures">
    </parameters>
    <parameters name="Shader Parameters Pass 0">
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/bloom.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         bloom.xml
  Description:  Contains the XML description of Bloom nodes.
  Author:       Simon Spielmann <sspielma@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="Bloom" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="BloomCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="BloomShader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Shader Parameters Pass 0">
      <parameter name="OriginalImageWeight" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="1.0" stepSize="0.001"/>
      <parameter name="BlurWeight" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.65" minValue="0.0" maxValue="1.0" stepSize="0.001"/>
      <parameter name="BlurWidthV" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.5" minValue="0.0" maxValue="3.0" stepSize="0.01"/>
      <parameter name="BlurWidthH" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.5" minValue="0.0" maxValue="3.0" stepSize="0.01"/>
    </parameters>
  </parameters>
</nodetype>
