=== FilmakademieRnd/Frapper/resources/nodetype.dtd
<!ELEMENT nodetype (parameter|parameters)*>
<!ATTLIST nodetype
	name			CDATA				#REQUIRED
	category (Animation|Cameras|Character|Compositing|Geometry|Images|Input|Lights|Network|Rendering|Shading|Tracking|Utility|S3D|Solver|rtSolver) 
										#REQUIRED
	color			CDATA				#REQUIRED
	plugin			CDATA				#REQUIRED
>

<!ELEMENT parameter (literal|separator)*>
<!ATTLIST parameter
	name			CDATA				#REQUIRED
	type			(Bool|Int|UnsignedInt|Float|String|Filename|Color|Enumeration|TextInfo|Command|Geometry|Light|Camera|Image|Group|PlugIn|Generic) 
										#REQUIRED
	size			CDATA	            #IMPLIED
    multiplicity	CDATA				#IMPLIED
    defaultValue	CDATA				#IMPLIED
    visible			(true|1|false|0)	#IMPLIED
    enabled			(true|1|false|0)	#IMPLIED
    readOnly		(true|1|false|0)	#IMPLIED
    selfEvaluating	(true|1|false|0)	#IMPLIED
    affects			CDATA				#IMPLIED
    description		CDATA				#IMPLIED
    unit			CDATA				#IMPLIED
    pin				(in|out)			#IMPLIED
    inputMethod		(SpinBox|SliderPlusSpinBox)	
										#IMPLIED
    minValue		CDATA				#IMPLIED
    maxValue		CDATA				#IMPLIED
    stepSize		CDATA				#IMPLIED
    filter			CDATA				#IMPLIED
>

<!ELEMENT literal EMPTY>
<!ATTLIST literal
	name			CDATA				#REQUIRED
	value			CDATA				#IMPLIED
>

<!ELEMENT parameters (parameter|parameters)*>
<!ATTLIST parameters
	name			CDATA				#IMPLIED
	enabled			(true|false)		#IMPLIED
    visible			(true|false)	#IMPLIED

>

<!ELEMENT separator EMPTY>

=== FilmakademieRnd/Frapper/plugins/nodes/Geometry/AnimatableMeshHair/animatablemeshhair.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--
  Project:      Filmakademie Application Framework
  File:         animatablemeshhair.xml
  Description:  Contains the XML description of AnimatableMeshHair nodes.
  Author:       Felix Bucella <felix.bucella@filmakademie.de>
				Markus Rapp <markus.rapp@web.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">

<nodetype name="AnimatableMeshHair" category="Geometry" color="7, 45, 87" plugin="animatablemeshhair.dll">
	<parameters>
		<parameters name="Hair Geometry">
			<parameter name="Geometry File" type="Filename" filter="Geometry Files (*.mesh)"/>
			<parameter name="Scalp Mesh Name" type="String" defaultValue="ScalpMesh" enabled="true" />
			<parameter name="Hair Guides Name" type="String" defaultValue="GuideStrip" enabled="true" />
			<parameter name="Combine Object IDs for Namespace" type="String" defaultValue="GuideStrip" enabled="true" />
			<parameter name="Distance Root Vertex to Scalp Vertex" type="Float" defaultValue="0.01" minValue="0.0"  maxValue="0.5" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="Assigned Bone Name" type="String" defaultValue="Head" enabled="true" />
			<parameter name="Hair Style Initial Position"  type="Float" size="3" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" stepSize="0.05"/>

			<parameter name="Single Strand" type="Bool" defaultValue="false"/>

			<parameter name="g_rootRadius" type="Float" defaultValue="0.5" minValue="0.0"  maxValue="1.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_tipRadius" type="Float" defaultValue="0.48" minValue="0.0"  maxValue="1.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_clumpWidth" type="Float" defaultValue="1.0" minValue="0.0"  maxValue="10.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>

			<parameter name="g_strandWidth" type="Float" defaultValue="0.01" minValue="0.001"  maxValue="0.5" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_strandTaperingStart" type="Float" defaultValue="2.0" minValue="0.0"  maxValue="64" stepSize="1.0" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_curlyHairScale" type="Float" defaultValue="0.0" minValue="0.0"  maxValue="5.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_deviationHairScale" type="Float" defaultValue="0.0" minValue="0.0"  maxValue="0.1" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_thinning" type="Float" defaultValue="0.5" minValue="0.0"  maxValue="1.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
		
			<parameter name="g_clumpTransitionLength" type="Float" defaultValue="1.0" minValue="0.0"  maxValue="1.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_maxDistance" type="Float" defaultValue="50.0" minValue="0.0"  maxValue="50.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_maxAngle" type="Float" defaultValue="360.0" minValue="0.0"  maxValue="360.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="Render Guide Strands" type="Bool" defaultValue="false"/>
			<parameter name="Render Scalp Mesh" type="Bool" defaultValue="false"/>
			
			<parameter name="Number of Hair Segments" type="TextInfo"/>
			<parameter name="Texture Size" type="TextInfo"/>
			<parameter name="Number of Guide Hairs" type="TextInfo"/>
			<parameter name="Clean empty Skeleton Animation tracks on load" type="Bool" defaultValue="true"/>
			<parameter name="Number of Vertices" type="TextInfo"/>
			<parameter name="Number of Triangles" type="TextInfo"/>
			<parameter name="useSaC" type="Bool" defaultValue="false"/>
			<parameter name="Use Spline Interpolation" type="Bool" defaultValue="false"/>
			<parameter name="mult" type="Float" defaultValue="1.0" maxValue="100000.0"/>
			<parameter name="manual" type="Bool" defaultValue="false"/>
			<parameter name="bones" type="Bool" defaultValue="false"/>
			<parameter name="manualMat" type="Bool" defaultValue="false"/>
			<parameter name="autoPose" type="Bool" defaultValue="true"/>
			<parameter name="Global Material Parameter Update" type="Bool" defaultValue="false"/>
		</parameters>
		<parameters name="Hair LOD">
			<parameter name="Hair LOD Factor" type="Float" defaultValue="1.0" minValue="0.0"  maxValue="2.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_tessellationFactor" type="Float" defaultValue="64.0" minValue="-1.0"  maxValue="64.0" stepSize="0.1" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_detailFactor" type="Float" defaultValue="2.0" minValue="-1.0"  maxValue="64.0" stepSize="0.1" inputMethod="SliderPlusSpinBox"/>
			<parameter name="g_backFaceCullingScale" type="Float" defaultValue="0.3" minValue="0.0"  maxValue="1.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="Screen Space Adaptive LOD" type="Bool" defaultValue="false"/>
			<parameter name="Segment Screen Size" type="Float" defaultValue="4.0" minValue="0.0"  maxValue="50.0" stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
			<parameter name="Bend Angle Meaningful" type="Float" defaultValue="5.0" minValue="0.0"  maxValue="45.0" stepSize="1.0" inputMethod="SliderPlusSpinBox"/>
			<parameter name="Bend Angle Max Tessellation" type="Float" defaultValue="45.0" minValue="0.0"  maxValue="180.0" stepSize="1.0" inputMethod="SliderPlusSpinBox"/>
		</parameters>
		<parameters name="Hair Shading">
      <parameter name="lightPower" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.01" maxValue="1" defaultValue="0.3" stepSize="0.01" description="Sets the intensity of the light"/>
			<parameter name="rootColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.4, 0.33, 0.27"/>
      <parameter name="tipColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.8, 0.67, 0.53"/>
      <parameter name="colorGradientWidth" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.01" maxValue="10" defaultValue="1.0" stepSize="0.01" description="Sets the gradients behaviour"/>
      <parameter name="colorGradientShift" type="Float" inputMethod="SliderPlusSpinBox" minValue="-1.0" maxValue="1.0" defaultValue="0.0" stepSize="0.01" description="Sets the gradients behaviour"/>
      <parameter name="diffuseColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.55, 0.4, 0.24"/>
			<parameter name="diffuseStrength" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="10" defaultValue="8.0" stepSize="0.01"/>
			<parameter name="reflectColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.9, 0.9, 0.9"/>
			<parameter name="reflectStrength" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="10" defaultValue="3.0" stepSize="0.01"/>
			<parameter name="reflectWidth" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1000" defaultValue="200" stepSize="1"/>
			<parameter name="reflectShift" type="Float" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" defaultValue="-5" stepSize="0.5"/>
			<parameter name="scatterColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.5, 0.2, 0.05"/>
			<parameter name="scatterStrength" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="10" defaultValue="3.0" stepSize="0.01"/>
			<parameter name="scatterWidth" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1000" defaultValue="0" stepSize="1"/>
			<parameter name="scatterShift" type="Float" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" defaultValue="7.5" stepSize="0.5"/>
			<parameter name="transmitColor" type="Color" inputMethod="SliderPlusSpinBox" minValue="0 0 0" maxValue="1 1 1" defaultValue="0.7, 0.4, 0.1"/>
			<parameter name="transmitStrength" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="10" defaultValue="3.0" stepSize="0.01"/>
			<parameter name="transmitWidth" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1000" defaultValue="25" stepSize="1"/>
			<parameter name="transmitShift" type="Float" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" defaultValue="2.5" stepSize="0.5"/>
		</parameters>
	</parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/lns.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         cld.xml
  Description:  Implementation of the coherent line drawing algorithm: "Coherent Line Drawing" - Kang et al. 2007
  Author:       Marc Spicker <marc.spicker@uni-konstanz.de>
  Copyright:    (c) 2014 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="LooseAndSketchyGPU" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="LNSCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="LNSShader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
	<parameters name="Shader Parameters Pass 0">
	  <parameter name="sigma" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.1" maxValue="30.0" defaultValue="10.0" stepSize="0.1" description="Sigma of Gaussian blur of input image."/>		
	  <parameter name="sigma2" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.1" maxValue="10.0" defaultValue="1.0" stepSize="0.1" description="Sigma of Gaussian blur of gradient map."/>		
	  <parameter name="edge_thresh" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1.0" defaultValue="0.1" stepSize="0.01" description="Edge detection threshold."/>
	  <parameter name="seed_thresh" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1.0" defaultValue="0.95" stepSize="0.01" description="Determines the number of stroke seeds."/>
	  <parameter name="line_length" type="Int" inputMethod="SliderPlusSpinBox" minValue="1" maxValue="500" defaultValue="100" stepSize="1"/>
	  <parameter name="mag_thresh" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="1.0" defaultValue="0.01" stepSize="0.001" description="Seeds in the vector field with a lower magnitude will get discarded."/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Rendering/HairRenderAlpha/hairrenderalpha.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         hairrenderalpha.xml
  Description:  Contains the XML description of SimpleRenderer nodes.
  Author:       Simon Spielmann <sspielma@filmakademie.de>
  Copyright:    (c) 2010 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="HairRendererAlpha" category="Rendering" color="173, 255, 173" plugin="hairrenderalpha.dll">
  <parameters>
    <parameters name="Light Definition">
      <parameter name="Light Description File" type="Filename" filter="Light Description Files (*.txt)"/>
      <parameter name="Light Scale Pos" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.1" maxValue="500" defaultValue="60" stepSize="0.1"/>
      <parameter name="lightPower" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.01" maxValue="1" defaultValue="0.1" stepSize="0.01"/>
      <parameter name="Number of Lights" type="Int" inputMethod="SliderPlusSpinBox" minValue="1" maxValue="16" defaultValue="1" stepSize="1"/>
    </parameters>
    <parameters name="Shadow Parameters">
      <parameter name="vsmEpsilon" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="2" defaultValue="0.0001" stepSize="0.0001"/>
      <parameter name="sampleRadius" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="20" defaultValue="2" stepSize="1"/>
      <parameter name="blurSize" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="10" defaultValue="1" stepSize=".1"/>
      <parameter name="LiSPSMAdjust" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.001" maxValue="1" defaultValue="0" stepSize="0.001"/>
      <parameter name="CamLightAngle" type="Float" inputMethod="SliderPlusSpinBox" minValue="1" maxValue="180" defaultValue="0" stepSize="1"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Utility/String2Bool/String2Bool.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         string2bool.xml
  Description:  Contains the XML description of String2Bool nodes.
  Author:       Volker Helzle (volker.helzle@filmakademie.de)
  Copyright:    (c) 2012 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="String2Bool" category="Utility" color="250,100,50" plugin="string2bool.dll">
  <parameters>
    <parameter name="Description" type="TextInfo" defaultValue="If intput string equals manually created output strings trigger corresponding bool output."/>
    <parameter name="Signal In" type="String" pin="in" visible="true" defaultValue="" selfEvaluating="true"/>        
    <parameter name="Number of Outputs" type="Int" defaultValue="11" selfEvaluating="true"/>
    <parameter name="Clean Output after 500ms" type="Bool" defaultValue="true" selfEvaluating="true"/>
    <parameter name="Clean All Outputs except triggered at once" type="Bool" defaultValue="false" selfEvaluating="true" description="clean all outputs, except the one that was activated"/>
    <parameter name="Clean All Outputs except triggered after 500ms" type="Bool" defaultValue="false" selfEvaluating="true"/>
    <parameters name="Outputs">
    </parameters>   
  </parameters>	
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Shading/WaterColor/WaterColor.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         watercolor.xml
  Description:  Contains the XML description of Watercolor nodes.
  Author:       Michael Bußler<@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-Württemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="WaterColorRes" category="Shading" color="7, 45, 87" plugin="ShadingTemplate.dll">
  <parameters>
    <parameter name="Shader Name" type="String" defaultValue="WaterColorShader"/>
    <parameter name="Resource Location" type="String" defaultValue="resources/WaterColor_Shader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Image" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Normal Map" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Depth Map" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="View Map" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Object Id Map" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Input Textures">
    </parameters>
    <parameters name="Shader Parameters Pass 0">
      <parameter name="OriginalImageWeight" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="1.0" stepSize="0.001"/>
      <parameter name="BlurWeight" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.65" minValue="0.0" maxValue="1.0" stepSize="0.001"/>
      <parameter name="BlurWidth" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="1.0" minValue="0.0" maxValue="3.0" stepSize="0.01"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Utility/S3DGame/s3dgame.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         s3dgame.xml
  Description:  Contains the XML description of S3DGame nodes.
  Author:       Michael Bußler <michael.bussler@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-Württemberg
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="S3DGame" category="Utility" color="40, 40, 40" plugin="S3DGame.dll">
  <parameters>
  <!-- input parameter -->
    <parameter name="P1_Action" type="Bool" description="Trigger Action of Player 1 (Jump)" pin="in" visible="true" selfEvaluating="true"/>
    <parameter name="P2_Action" type="Bool" description="Trigger Action of Player 1 (Move Forward)" pin="in" visible="true" selfEvaluating="true"/>
    <parameter name="Time"      type="Int"  description="System time from Timer node" pin="in" visible="false"/>

    <parameters name="Input Level" visible="false">
      <parameter name="Level"    description="The Input Level Geometry"      type="Geometry" pin="in" visible="false"/>
      <parameter name="Player1"  description="Additional Level Geometry only shown to Player 1"      type="Geometry" pin="in" visible="false"/>
      <parameter name="Player2"  description="Additional Level Geometry only shown to Player 2"      type="Geometry" pin="in" visible="false"/>
      <parameter name="Logic"    description="The Input Game Logic Geometry"      type="Geometry" pin="in" visible="false"/>
      <parameter name="ObjectMarker" description="Additional Geometry for Object Markers"  type="Geometry" pin="in" visible="false"/>
    </parameters>

    <parameter name="PlayerCharacter" description="The Player Character Geometry"     type="Geometry" pin="in" multiplicity="*"/>
    <parameter name="PlayerCharacterLight" description="Additional Lights attached to the Player Character" type="Light"    pin="in" multiplicity="*"/>

    <parameter name="Reset1" type="Bool" description="Resets the Game if triggered with Reset2" pin="in" defaultValue="false" selfEvaluating="true" visible="false"/>
    <parameter name="Reset2" type="Bool" description="Resets the Game if triggered with Reset1" pin="in" defaultValue="false" selfEvaluating="true" visible="false"/>
    
    <parameter name="Copy Animated Objects" type="Command"/>
    <parameter name="Reset" type="Command"/>
    <parameters name="Animated Objects">
      <parameter name="Platform1"       type="Geometry" pin="in" />
      <parameter name="Platform2"       type="Geometry" pin="in" />
      <parameter name="Door"            type="Geometry" pin="in" />
      <parameter name="Windwheel"       type="Geometry" pin="in" />
      <parameter name="Windwheel_Small" type="Geometry" pin="in" />
      <parameter name="Sign"            type="Geometry" pin="in" />
      <parameter name="Wheel"           type="Geometry" pin="in" />
      <parameter name="Windwheel_Big"   type="Geometry" pin="in" />
    </parameters>

    <!-- putput parameter -->
    <parameter name="ShowGameLogic"     type="Bool" description="Show Game Logic in Viewport"   defaultValue="false"/>
    <parameter name="ShowLightGeometry" type="Bool" description="Show Light Geometry in Viewport"   defaultValue="true"/>
    <parameter name="StepSize"       type="Int" description="The Step Size (Timing) of the Game" minValue="10"   maxValue="100"    defaultValue="40"     stepSize="1"   inputMethod="SliderPlusSpinBox"/>
    <parameter name="IntervalLength" type="Int" description="The Interval Length of a Path" minValue="1"    maxValue="100"    defaultValue="20"    stepSize="10" inputMethod="SliderPlusSpinBox"/>
    <parameter name="PCScale"        type="Float" description="The Size of the Player Character" minValue="0.1"  maxValue="10.0"   defaultValue="0.5"    stepSize="0.1" inputMethod="SliderPlusSpinBox"/>
    <parameter name="AnimScale"      type="Float" description="The Scale of the Animation Parameters" minValue="1.0"  maxValue="1000.0" defaultValue="100.0"  stepSize="1.0" inputMethod="SliderPlusSpinBox"/>
    <parameter name="LavaStep"       type="Float" description="The Step Size for the Lava Shader" minValue="0.001"  maxValue="0.2"   defaultValue="0.01"   stepSize="0.001" inputMethod="SliderPlusSpinBox"/>
    <parameter name="JumpAnimLength" type="Int" description="Length of the Jump Animation"  minValue="50"   maxValue="1000"   defaultValue="300"    stepSize="50"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="WalkAnimLength" type="Int" description="Length of the Walk Cycle Animation"  minValue="50"   maxValue="1000"   defaultValue="300"    stepSize="50"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="FallAnimLength" type="Int" description="Length of the Fall Animation"  minValue="50"   maxValue="1000"   defaultValue="300"    stepSize="50"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="DeathAnimLength" type="Int" description="Length of the Death Animation" minValue="50"   maxValue="2000"   defaultValue="1000"    stepSize="50"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="Platform1Time" type="Int" description="Timing of Platform 1"  minValue="50"   maxValue="1000"   defaultValue="1000"    stepSize="100"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="Platform2Time" type="Int" description="Timing of Platform 2"  minValue="50"   maxValue="1000"   defaultValue="2000"    stepSize="100"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="Platform3Time" type="Int" description="Timing of Platform 3"  minValue="50"   maxValue="1000"   defaultValue="2000"    stepSize="100"  inputMethod="SliderPlusSpinBox"/>
    <parameter name="StartPath"     type="String" description="The Name of Path where the Game starts" defaultValue="Path1" />
    <parameter name="CameraTranslate" type="Float" description="Additional translation of Camera attached to Player Character" size="3" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" defaultValue="0, 0, 0" stepSize="0.25" />
    
  <!-- output parameter -->
    <parameter name="Timer" type="Generic" description="Trigger Update from Timer Node" pin="out" />
    <parameter name="Stopwatch" type="String" description="Current Game Time as String" pin="out" />

    <!-- output animations -->
    <parameters name="Animations">
      <parameter name="DeathAnim"     type="Float" pin="out" visible="false"/>
      <parameter name="WalkAnim"      type="Float" pin="out" visible="false"/>
      <parameter name="JumpAnim"      type="Float" pin="out" visible="false"/>
      <parameter name="FallAnim"      type="Float" pin="out" visible="false"/>
      <parameter name="DiveAnim"      type="Float" pin="out" visible="false"/>
      <parameter name="JumpStartAnim" type="Float" pin="out" visible="false"/>
      <parameter name="JumpEndAnim"   type="Float" pin="out" visible="false"/>
      <parameter name="DoorOpenAnim"  type="Float" pin="out" visible="false"/>
      <parameter name="Platform1Anim" type="Float" pin="out" visible="false"/>
      <parameter name="Platform2Anim" type="Float" pin="out" visible="false"/>
      <parameter name="Platform3Anim" type="Float" pin="out" visible="false"/>
      <parameter name="Rings"         type="Float" pin="out" visible="false" defaultValue="100.0"/>
      <parameter name="EndScreen"     type="Float" pin="out" visible="false" defaultValue="0.0"/>
      <parameter name="WaitIdleAnim"  type="Bool"  pin="out" visible="false"/>
      <parameter name="JumpIdleAnim"  type="Bool"  pin="out" visible="false"/>
    </parameters>

    <!-- output geometry -->
    <parameters name="Output Geometry">
      <parameter name="Game_P1"   type="Geometry" description="Geometry to be shown to Player 1" pin="out" />
      <parameter name="Game_P2"   type="Geometry" description="Geometry to be shown to Player 2" pin="out" />
      <parameter name="Game_Both" type="Geometry" description="Geometry to be shown to Both Players" pin="out" />
    </parameters>
    <parameters name="PlayerCharacterData">
      <parameter name="Position"    type="Float" description="Current Position of the Player Character for Camera Node" size="3" minValue="-100" maxValue="100" defaultValue="0, 0, 0" stepSize="1.0" pin="out" visible="false"/>
      <parameter name="Orientation" type="Float" description="Current Orientation of the Player Character for Camera Node" size="3" minValue="-360" maxValue="360" defaultValue="0, 0, 0" stepSize="1.0" pin="out" visible="false"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/depth2stereo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         depth2stereo.xml
  Description:  Contains the XML description of Depth3Stereo node.
  Author:       Simon Spielmann <simon.spielmann@filmakademie.de>
  Copyright:    (c) 2013 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="Depth2Stereo" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="Depth2StereoCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="Depth2Stereo"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map RGB" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Input Map Z" type="Image" pin="in" selfEvaluating="false"/>
    </parameters> 
    <parameters name="Shader Parameters Pass 0">
      <parameter name="eyeDistance" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.0" minValue="-0.1" maxValue="0.1" stepSize="0.001"/>
      <parameter name="hit" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="0.0" minValue="-1" maxValue="1" stepSize="0.01"/>
    </parameters>
  </parameters>
</nodetype>
