=== FilmakademieRnd/Frapper/resources/nodetype.dtd
<!ELEMENT nodetype (parameter|parameters)*>
<!ATTLIST nodetype
	name			CDATA				#REQUIRED
	category (Animation|Cameras|Character|Compositing|Geometry|Images|Input|Lights|Network|Rendering|Shading|Tracking|Utility|S3D|Solver|rtSolver) 
										#REQUIRED
	color			CDATA				#REQUIRED
	plugin			CDATA				#REQUIRED
>

<!ELEMENT parameter (literal|separator)*>
<!ATTLIST parameter
	name			CDATA				#REQUIRED
	type			(Bool|Int|UnsignedInt|Float|String|Filename|Color|Enumeration|TextInfo|Command|Geometry|Light|Camera|Image|Group|PlugIn|Generic) 
										#REQUIRED
	size			CDATA	            #IMPLIED
    multiplicity	CDATA				#IMPLIED
    defaultValue	CDATA				#IMPLIED
    visible			(true|1|false|0)	#IMPLIED
    enabled			(true|1|false|0)	#IMPLIED
    readOnly		(true|1|false|0)	#IMPLIED
    selfEvaluating	(true|1|false|0)	#IMPLIED
    affects			CDATA				#IMPLIED
    description		CDATA				#IMPLIED
    unit			CDATA				#IMPLIED
    pin				(in|out)			#IMPLIED
    inputMethod		(SpinBox|SliderPlusSpinBox)	
										#IMPLIED
    minValue		CDATA				#IMPLIED
    maxValue		CDATA				#IMPLIED
    stepSize		CDATA				#IMPLIED
    filter			CDATA				#IMPLIED
>

<!ELEMENT literal EMPTY>
<!ATTLIST literal
	name			CDATA				#REQUIRED
	value			CDATA				#IMPLIED
>

<!ELEMENT parameters (parameter|parameters)*>
<!ATTLIST parameters
	name			CDATA				#IMPLIED
	enabled			(true|false)		#IMPLIED
    visible			(true|false)	#IMPLIED

>

<!ELEMENT separator EMPTY>

=== FilmakademieRnd/Frapper/plugins/nodes/Utility/ParticleSystemLogic/particlesystemlogic.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         ExpressionTimer.xml
  Description:  Contains the XML description of ExpressionTimer nodes.
  Author:       Stefan Habel <stefan.habel@filmakademie.de>, Nils Zweiling <nils.zweiling@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="ParticleSystemLogic" category="Utility" color="250,100,50" plugin="particlesystemlogic.dll">
  <parameters>
    <parameter name="Viseme Index" 	  type="Float"  defaultValue="0.0"  selfEvaluating="true" pin="in"/>
    <parameter name="Viseme Tag" 	    type="String" defaultValue=""     selfEvaluating="true" pin="in"/>
    <parameter name="Emotion Tag" 	  type="String" defaultValue=""     selfEvaluating="true" pin="in"/>    
    <parameter name="Ready"           type="Bool"   defaultValue="true" selfEvaluating="true" pin="in"/>
    <parameter name="Active"          type="Bool"   defaultValue="true" selfEvaluating="true" pin="in"/>

    <parameter name="Expressions XML" type="String" defaultValue=""     selfEvaluating="true" pin="out"/>
    <parameter name="Viseme is open"  type="Bool"   defaultValue="false"  selfEvaluating="true" pin="out" />
    <parameter name="Mouth Force"     type="Float"  defaultValue="0.0"  selfEvaluating="true" pin="out" />
    <parameter name="Mesh Force"      type="Float"  defaultValue="0.0"  selfEvaluating="true" pin="out" />
    <parameter name="Inter Particle Force"      type="Float"  defaultValue="0.1"  selfEvaluating="true" pin="out" />
    
  </parameters>
   
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/pencildrawing.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         pencildrawing.xml
  Description:  Implementation of the pencil drawing rithm: "Combining Sketch and Tone for Pencil Drawing Production" - Lu et al. 2012
  Author:       Marc Spicker <marc.spicker@uni-konstanz.de>
  Copyright:    (c) 2014 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="PencilDrawing" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="PencilDrawingCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="PencilDrawingShader"/>    
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>	
	  <parameters name="Shader Parameters Pass 0">
		  <parameter name="Monochrome" type="Int" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="1" defaultValue="0" stepSize="1"/>
		  <parameter name="KernelRatio" type="Float" inputMethod="SliderPlusSpinBox" minValue="1.0" maxValue="500.0" defaultValue="200.0" stepSize="1.0" description="Maximum side (width or height) of the image divided by this factor results in the kernel width"/>
		  <parameter name="W1" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="100.0" defaultValue="11.0" stepSize="1.0" description="Weight of Tone Model 1"/>
		  <parameter name="W2" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="100.0" defaultValue="37.0" stepSize="1.0" description="Weight of Tone Model 2"/>
		  <parameter name="W3" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="100.0" defaultValue="52.0" stepSize="1.0" description="Weight of Tone Model 3"/>
    </parameters>
    <parameters name="Predefined Values">
      <parameter name="Preset" type="Enumeration" defaultValue="No Preset"  description="values are 'Monochrome x KernelRatio x W1 x W2 x W3' ">
        <literal name="No Preset" />
        <literal name="Low Abstraction"     value="0 x 325 x 11 x 37 x 52" />
        <literal name="Medium Abstraction"  value="0 x 200 x 11 x 37 x 52" />
        <literal name="High Abstraction"    value="0 x 120 x 11 x 37 x 52" />
      </parameter>
      <parameter name="Preset Index" type="Float" defaultValue="0.0" pin="in" selfEvaluating="true" />
    </parameters>
    
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Npr/FilterBilateralSmooth/filterbilateralsmooth.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         filterbilateralsmooth.xml
  Description:  Contains the XML description of FilterBilateralSmooth nodes.
  Author:       Thomas Luft <thomas.luft@web.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="FilterBilateralSmooth" category="Compositing" color="185, 30, 75" plugin="filterbilateralsmooth.dll">
  <parameters>
    <parameter name="Input Map" type="Image" pin="in" selfEvaluating="true"/>
    <parameter name="Resource Group Name" type="String" defaultValue="BilateralSmooth" visible="false"/>
    <parameter name="Reload" type="Command" />
      <parameters name="Polish">
      <parameter name="Smoothness" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="100.0" defaultValue="50.0" unit=""/>
      <parameter name="Details" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.0" maxValue="100.0" defaultValue="50.0" unit=""/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Compositing/CompositorTemplate/skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         skin.xml
  Description:  Contains the XML description of Skin node.
  Author:       Michael Heberlein <michael.heberlein@filmakademie.de>
  Copyright:    (c) 2011 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="Skin" category="Compositing" color="185, 30, 75" plugin="compositortemplate.dll">
  <parameters>
    <parameter name="Compositor Name" type="String" defaultValue="SkinCompositor"/>
    <parameter name="Resource Group Name" type="String" defaultValue="SkinShader"/>
    <parameter name="Reload" type="Command"/>
    <parameters name="Input Maps">
      <parameter name="Input Map Scene" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Input Map Depth" type="Image" pin="in" selfEvaluating="false"/>
      <parameter name="Input Map IDs" type="Image" pin="in" selfEvaluating="false"/>
    </parameters>
    <parameters name="Shader Parameters Pass 0">
	  <parameter name="sssWidth" type="Float" inputMethod="SliderPlusSpinBox" defaultValue="5.0" minValue="0.0" maxValue="25.0" stepSize="0.1"/>
	  <parameter name="skinId" type="Float" defaultValue="8" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="32" stepSize="0.5"/>
	  <parameter name="correction" type="Float" defaultValue="300" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="1000" stepSize="1"/>
    </parameters>
	
  </parameters>
  
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Utility/Transform/transform.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         transform.xml
  Description:  Contains the XML description of Transform nodes.
  Author:       Stefan Habel <stefan.habel@filmakademie.de>, Nils Zweiling <nils.zweiling@filmakademie.de>
  Copyright:    (c) 2009 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="Transform" category="Utility" color="255, 192, 171" plugin="transform.dll">
  <parameters>
    <parameters name="Transformation">
      <parameter name="Translate" type="Float" size="3" inputMethod="SliderPlusSpinBox" minValue="-100" maxValue="100" stepSize="0.05" pin="in"/>
      <parameter name="Rotate" type="Float" size="3" inputMethod="SliderPlusSpinBox" minValue="-360" maxValue="360" stepSize="0.01" pin="in"/>
      <parameter name="Scale" type="Float" size="3" inputMethod="SliderPlusSpinBox" minValue="-10" maxValue="10" stepSize="0.01" defaultValue="1, 1, 1" pin="in"/>
     </parameters>
    <parameter name="Geometry to Transform" type="Geometry" multiplicity="*" pin="in"/>
    <parameter name="Light to Transform" type="Light" multiplicity="*" pin="in"/>
    <parameter name="Camera to Transform" type="Camera" multiplicity="*" pin="in"/>
    <parameter name="Transformed Geometry" type="Geometry" pin="out"/>
    <parameter name="Transformed Light" type="Light" pin="out"/>
    <parameter name="Transformed Camera" type="Camera" pin="out"/>
	  <parameter name="Reset" type="Command" />
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Rendering/ShadowMapHairRender/shadowmaphairrender.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         shadowmaprender.xml
  Description:  Contains the XML description of SimpleRenderer nodes.
  Author:       Markus Rapp <markus.rapp@filmakademie.de>
  Copyright:    (c) 2014 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="ShadowMapHairRenderer" category="Rendering" color="173, 255, 173" plugin="shadowmaphairrender.dll">
  <parameters>
    <parameters name="Light Definition">
      <parameter name="lightPower" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.01" maxValue="1" defaultValue="0.1" stepSize="0.01"/>
      <parameter name="Number of Lights" type="Int" inputMethod="SliderPlusSpinBox" minValue="1" maxValue="16" defaultValue="4" stepSize="1"/>
    </parameters>
    <parameters name="Shadow Parameters">
      <parameter name="vsmEpsilon" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="2" defaultValue="0.0001" stepSize="0.0001"/>
      <parameter name="sampleRadius" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="20" defaultValue="2" stepSize="1"/>
      <parameter name="blurSize" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="10" defaultValue="1" stepSize=".1"/>
      <parameter name="scaleBias" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="1" defaultValue="0" stepSize="0.001"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Rendering/HairRender/hairrender.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         hairrender.xml
  Description:  Contains the XML description of SimpleRenderer nodes.
  Author:       Simon Spielmann <sspielma@filmakademie.de>
  Copyright:    (c) 2010 Filmakademie Baden-WÃ¼rttemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="HairRenderer" category="Rendering" color="173, 255, 173" plugin="hairrender.dll">
  <parameters>
    <parameters name="Light Definition">
      <parameter name="Light Description File" type="Filename" filter="Light Description Files (*.txt)"/>
      <parameter name="Light Scale Pos" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.1" maxValue="100" defaultValue="1" stepSize="0.1"/>
      <parameter name="lightPower" type="Float" inputMethod="SliderPlusSpinBox" minValue="0.01" maxValue="1" defaultValue="0.1" stepSize="0.01"/>
      <parameter name="Number of Lights" type="Int" inputMethod="SliderPlusSpinBox" minValue="1" maxValue="16" defaultValue="4" stepSize="1"/>
    </parameters>
    <parameters name="Shadow Parameters">
      <parameter name="sampleRadius" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="20" defaultValue="2" stepSize="1"/>
      <parameter name="blurSize" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="10" defaultValue="1" stepSize=".1"/>
      <parameter name="scaleBias" type="Float" inputMethod="SliderPlusSpinBox" minValue="0" maxValue="50000" defaultValue="0" stepSize="100"/>
      <parameter name="biasOffset" type="Float" inputMethod="SliderPlusSpinBox" minValue="-10000" maxValue="10000" defaultValue="0" stepSize="100"/>
    </parameters>
  </parameters>
</nodetype>

=== FilmakademieRnd/Frapper/plugins/nodes/Cameras/StereoCamera/stereocamera.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Project:      Filmakademie Application Framework
  File:         stereocamera.xml
  Description:  Contains the XML description of StereoCamera nodes.
  Author:       Michael Bußler <michael.bussler@filmakademie.de>
  Copyright:    (c) 2010 Filmakademie Baden-Württemberg
  Hint:         You can use Visual Studio to edit the file. It helps following the rules of the document type
                definition from the nodetype.dtd file.
-->

<!DOCTYPE nodetype SYSTEM "../../../nodetype.dtd">
<nodetype name="StereoCamera" category="Cameras" color="173, 255, 173" plugin="stereocamera.dll">
  <parameters>
	<parameters name="Stereo">
      <parameter name="Eye Distance" type="Float" defaultValue="0.3" stepSize="0.1"/>
      <parameter name="Reverse Stereo" type="Bool" />
      <parameter name="Frustum Offset Multiplier" type="Float" defaultValue="1.0"/>
      <parameter name="Focal Length" type="Float" defaultValue="24.0" pin="out"/>
      <parameter name="Field of View" type="Float" defaultValue="66.0" minValue="0" maxValue="179,99" pin="out"/>
  </parameters>
  </parameters>
</nodetype>
